# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IJSGPUImageSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IJSGPUImageSDK

  target 'IJSGPUImageSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IJSGPUImageSDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'GPUImage'




end
